#!/bin/bash
wget -O - https://packages.pagerduty.com/GPG-KEY-pagerduty | apt-key add -
sh -c 'echo "deb https://packages.pagerduty.com/pdagent deb/" >/etc/apt/sources.list.d/pdagent.list'
apt-get update && apt-get install -yq pdagent pdagent-integrations
echo "ok"
