#!/bin/sh
# This is a sample shell script showing how you can submit the DISABLE_HOST_SVC_CHECKS command
# to Nagios.  Adjust variables to fit your environment as necessary.

now=`date +%s`
commandfile='/opt/nagios/var/rw/nagios.cmd'
host=$1
status=$2
downtime=$3

if [ $status = 0 ]; then
        /usr/bin/printf "[%lu] ENABLE_HOST_SVC_CHECKS;$host\n" $now > $commandfile;
        export IFS=';'
        for service in `/opt/nagios/libexec/perl.pl /opt/nagios/etc/nagios.cfg $host`
        do


        /usr/bin/printf "[%lu] PROCESS_SERVICE_CHECK_RESULT;$host;$service;0\n" $now > $commandfile;
        done
        echo $downtime > /tmp/downtime.txt;
elif [ $status = 1 ]; then
        /usr/bin/printf "[%lu] DISABLE_HOST_SVC_CHECKS;$host\n" $now > $commandfile;
        export IFS=';'
        for service in `/opt/nagios/libexec/perl.pl /opt/nagios/etc/nagios.cfg $host`
        do
                /usr/bin/printf "[%lu] PROCESS_SERVICE_CHECK_RESULT;$host;$service;3;Servico Nao Checado\n" $now > $comman
dfile;
        done
        echo $downtime > /tmp/downtime.txt;
fi
