#!/bin/sh
# This is a sample shell script showing how you can submit the DISABLE_HOST_SVC_CHECKS command
# to Nagios.  Adjust variables to fit your environment as necessary.
now=`date +%s`
commandfile='/opt/nagios/var/rw/nagios.cmd'
host=$1
status=$2
downtime=$3
if [ $status = 0 ]; then
        services=$(/opt/nagios/libexec/perl.pl /opt/nagios/etc/nagios.cfg $host)
        while IFS= read -r service
        do
        /usr/bin/printf "[%lu] ENABLE_HOST_SVC_CHECKS;$host\n" $now > $commandfile;
        /usr/bin/printf "[%lu] PROCESS_SERVICE_CHECK_RESULT;$host;$service;0\n" $now > $commandfile;
        done <<< "$services"
        echo $downtime > /tmp/downtime.txt;

elif [ $status = 1 ]; then
        services=$(/opt/nagios/libexec/perl.pl /opt/nagios/etc/nagios.cfg $host)
        while IFS= read -r service
        do
                /usr/bin/printf "[%lu] DISABLE_HOST_SVC_CHECKS;$host\n" $now > $commandfile;
                /usr/bin/printf "[%lu] PROCESS_SERVICE_CHECK_RESULT;$host;$service;3;Servico Nao Checado\n" $now > $commandfile;
        done <<< "$services"
        echo $downtime > /tmp/downtime.txt;

fi
